-- 51. Display Customer Name, Customer Email, Order ID, Product Name and Quantity for every order.
SELECT
c.first_name,
c.last_name,
c.email,
o.order_id,
p.product_name,
oi.quantity
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id;

-- 52. Display Customer Name, City, Order Date, Product Name, Product Category and Item Total for all orders.
SELECT
c.first_name,
c.last_name,
c.city,
o.order_date,
p.product_name,
p.category,
oi.item_total
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id;

-- 53. Display Customer Name, Order ID, Product Name, Brand, Quantity and Unit Price for every order.
SELECT
c.first_name,
c.last_name,
o.order_id,
p.product_name,
p.brand,
oi.quantity,
oi.unit_price
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id;

-- 54. Display customer name, product name, order status and payment method for all orders.
SELECT
c.first_name,
c.last_name,
p.product_name,
o.order_status,
o.payment_method
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id;

-- 55. Display customer name, customer city, product name, category and item total for delivered orders.
SELECT
c.first_name,
c.last_name,
c.city,
p.product_name,
p.category,
oi.item_total
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id
WHERE o.order_status = 'Delivered';

-- 56. Identify customers who purchased products worth more than 20,000. Display Customer Name, Product Name, Order Date and Item Total.
SELECT
c.first_name,
c.last_name,
p.product_name,
o.order_date,
oi.item_total
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id
WHERE oi.item_total > 20000;

-- 57. Find all products purchased by customers from Maharashtra. Display Customer Name, City, Product Name and Category.
SELECT DISTINCT
c.first_name,
c.last_name,
c.city,
p.product_name,
p.category
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id
WHERE c.state = 'Maharashtra';

-- 58. Find all products purchased using UPI. Display Customer Name, Product Name, Order Date, Payment Method and Item Total.
SELECT
c.first_name,
c.last_name,
p.product_name,
o.order_date,
o.payment_method,
oi.item_total
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id
WHERE o.payment_method = 'UPI';

-- 59. Find all products purchased by customers whose status is Active. Display Customer Name, Product Name, Order Status and Item Total.
SELECT
c.first_name,
c.last_name,
p.product_name,
o.order_status,
oi.item_total
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id
WHERE c.customer_status = 'Active';

-- 60. Find all cancelled orders and display Customer Name, Order ID, Product Name, Order Status and Item Status.
SELECT
c.first_name,
c.last_name,
o.order_id,
p.product_name,
o.order_status,
oi.item_status
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id
WHERE o.order_status = 'Cancelled' OR oi.item_status = 'Cancelled';

-- 61. Calculate the total amount spent by each customer. Display Customer ID, Customer Name and Total Purchase Amount. Use SUM() and GROUP BY.
SELECT
c.customer_id,
c.first_name,
c.last_name,
SUM(oi.item_total) AS total_purchase_amount
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name;

-- 62. Find the total quantity of products sold in each category. Display Category and Total Quantity Sold.
SELECT
p.category,
SUM(oi.quantity) AS total_quantity_sold
FROM products p
INNER JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.category;

-- 63. Find the total sales generated by each product. Display Product ID, Product Name, Category and Total Sales. Sort by total sales descending.
SELECT
p.product_id,
p.product_name,
p.category,
SUM(oi.item_total) AS total_sales
FROM products p
INNER JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name, p.category
ORDER BY total_sales DESC;

-- 64. Find the total revenue generated from Delivered orders for every customer. Display Customer ID, Customer Name, Number of Orders and Total Revenue. Use JOIN, WHERE, GROUP BY, COUNT(), SUM() and ORDER BY.
SELECT
c.customer_id,
c.first_name,
c.last_name,
COUNT(DISTINCT o.order_id) AS number_of_orders,
SUM(oi.item_total) AS total_revenue
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- 65. Generate a complete Customer Purchase Report with Customer ID, Customer Name, Email, City, Order ID, Order Date, Order Status, Product Name, Category, Quantity, Unit Price, Discount, Tax, Item Total and Payment Method. Only include Delivered orders. Sort by Customer Name ASC and Order Date DESC.
SELECT
c.customer_id,
c.first_name,
c.last_name,
c.email,
c.city,
o.order_id,
o.order_date,
o.order_status,
p.product_name,
p.category,
oi.quantity,
oi.unit_price,
oi.discount,
oi.tax,
oi.item_total,
o.payment_method
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id
WHERE o.order_status = 'Delivered'
ORDER BY c.first_name ASC, c.last_name ASC, o.order_date DESC;

